[package]
name = "minigolf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
num-derive = "0.3"
thiserror = "1.0"
chrono = "0.4.26"
anyhow = "1.0"
bitflags = "2.3.1"
